### ISSUE TITLE
Silent fail of LearnSequenceReferencingSibling example in WranglingSamples

### ISSUE THREAD

**Issue by eglassman** [Microsoft/prose#10]
The LearnSequenceReferencingSibling example in WranglingSamples does not print anything. In the following code (linked here: https://github.com/Microsoft/prose/blob/master/Extraction.Text/LearningSamples.cs#L388-L393), instead of iterating over the regions as in prior documentation examples found in https://microsoft.github.io/prose/documentation/extraction-text/usage/#extracting-a-sequence-of-stringregions
like this:
```
foreach (var r in topRankedProg.Run(countries))
{
    var output = r.Output != null ? r.Output.Value : "null";
    Console.WriteLine("\"{0}\" => \"{1}\"", r.Reference, output);
}
```
it iterates over a much more complicated expression, which returns an empty list:
```
foreach (var a in areas
                .SelectMany(area => topRankedProg.Run(area)
                                                    .Select(output => new { Input = area, Output = output }))) {
                var output = a.Output != null ? a.Output.Value : "null";
                Console.WriteLine("\"{0}\" => \"{1}\"", a.Input, output);
            }
```
I tried changing this example to iterate over `topRankedProg.Run(areas)` so it's more like the example in the documentation, but the object returned by `topRankedProgram.Run( )` does not out an output field.
Help?

**Comment by vuminhle** [comment]
Hi. We are updating the samples and the documentation. 
Please stay tuned. Thanks for your patience.

**Comment by vuminhle** [comment]
@eglassman The new samples and documentation have been released. 
Can you try again? Thanks.

**Comment by apskim** [comment]
With release 1.1.0, we are making the public API for interacting with DSLs more intuitive. Please check out [the new `LearnSequenceReferencingSibling` sample](https://github.com/Microsoft/prose/blob/master/Extraction.Text/LearningSamples.cs#L457-L499).
