### ISSUE TITLE
Several issues with the tutorials

### ISSUE THREAD

**Issue by DarkMatter222** [Microsoft/prose#2]
Hello and thank you for creating the PROSE SDK! I was very excited to find out about it. 

I tried to work through the "Getting started" tutorial and the example on the "Framework" page, and found several typos and other little bugs. I will list them all here and I hope some of those will be helpful for improving the tutorials.

1. Framework https://microsoft.github.io/prose/documentation/prose/usage/
 * The language definition has an x missing at line 9: in its semantics definition, ```CPos``` depends on two variables - a string s and an int k, so I suppose line 9 should be ```int P := CPos(x,k) | Pos(x, r, r, k); ```
 * In the grammar, ```SubStr``` takes a string a two integers, while in the semantics - a string and an int tuple. I changed the semantics function to be ```public static string SubStr(string s, int left, int right){...}```
 * Similarly, in the grammar ```Pos``` takes a string, two Regex, and and int, and in the semantics - a string, a Regex tuple and an int. I changed the semantics function to be ```public static int? Pos(string s, Regex leftRegex, Regex rightRegex, int occurrence){...}``` 
 * Some minor things
   * in ```Pos```, ```.FormatWith()``` doesn't work for me, so I used ```String.Format()```
    * in ```SubStr```, ```.Slice()``` doesn't work for me, so I used ```.Substring()```

2. Getting started https://microsoft.github.io/prose/documentation/prose/tutorial/
 * In Semantics: ```Match``` doesn't have a ```Right``` property. ```m.Right``` should be ```m.Index``` ? 
 * In WitnessFunctions:
   * In several places ```ExampleSpecification``` (or ```DisjunctiveExamplesSpecification```) should be ```ExampleSpec``` (or ```DisjunctiveExamplesSpec```).
    * There are a few casts missing (that can't be implicit). E.g. in ```AbsolutePosition```, ```result[inputState] = ks;``` should be ```result[inputState] = ((IEnumerable<int?>)ks).Cast<object>();```, but I guess for the tutorial is better to be simpler in syntax.
    * As in Semantics, ```Match``` doesn't have a ```Right``` property. ```m.Right``` should be ```m.Index``` ?
    * I'm not entire surely what's going on the the ```WitnessRegexPair``` function, but the values of ```leftMatches``` and ```rightMatches``` are list of Matches, while the regex list we add to the result is of Regex tuples, rather than Match tuples. In ```BuildStringMatches```, shouldn't we keep track of the regexes we've used?
    * ```WitnessKForRegexPair``` should take a ```GrammarRule``` rather than a ```Grammar```? 
    * Minor: ```BuildStringMatches()``` should be static.

**Comment by apskim** [comment]
Thanks for the report! We'll fix the typos/bugs. Meanwhile, here are some answers to your immediate questions:
* `Slice` is an extension method replicating Python's "slicing". Its integer parameters are `start` and `end` of the desired substring. In contrast, `Substring`'s integer parameters are `start` and `length` of the desired substring. Which one you choose is a matter of preference, but please ensure that the semantics of an operator is consistent with its witness function.
* Similarly, `Right` is a shortcut for `Index + Length`.
* `ks.Cast<object>()` is sufficient for all places where LINQ conversion is required.
* `WitnessRegexPair` has a bug and needs to be rewritten, thank you.
