### ISSUE TITLE
Is there an ignore case option?

### ISSUE THREAD

**Issue by dfinke** [Microsoft/prose#23]
If I pass a lower case `pe5` as the last argument, Pprose throws the error below. Is there an `ignore case` option that can be specified?

```csharp
splitSession.Constraints.Add(new NthExampleConstraint(inputs[0].Value, 0, "PE5"));
```

```
"The example value is not a substring of the input"
```

**Comment by simmdan** [comment]
Hi Doug,

Thanks for bringing this up.  Unfortunately we don't have that sort of option right now, but we have done something similar for a partner team in another DSL.  So this reinforces the interest that may lead to us doing something like this in the future.

In the meantime, it's not ideal, but you could do a case-insensitive search in the input and if you find a result, change the example to match the input...

- Danny
