### ISSUE TITLE
Semantic Transformation with Multiple Lookups

### ISSUE THREAD

**Issue by aslihanozmen** [microsoft/prose#30]
Hello, 
First of all, thank you for creating PROSE and making it publicly available.
I am aware that PROSE is able to perform semantic transformation for parsing the dates and rounding the numbers, and I assume that in the background these dates and numbers are defined explicitly to the framework in order to find the match in the relevant table. However, my question is if my transformation requires multiple lookups to other tables, how can I add these related tables directly to PROSE? According to my understanding, FlashFill DSL is powerful enough to enable this kind of semantic transformation, but I'm not quite sure that how I can explicitly add these relevant tables to learning session in PROSE. 
Thank you!

**Comment by danpere** [comment]
Thank you for your interest. Unfortunately, despite the fact that, as you say, it's theoretically possible, Transformation.Text as presently implemented in PROSE does not support custom lookup functions.

What do you want to use them for? How expressive do you need the language to be? (e.g. Do you only need to look up a substring of the input in a dictionary and concat it into the output? Or do you want a custom function that does some computation? Or do you ever need to perform a lookup on the result of a lookup? Or a lookup based on some other computation done on the input string like a casing transformation?)

**Comment by aslihanozmen** [comment]
Thank you for your quick reply.  The best and complex example would be Figure 1 in [this](https://arxiv.org/pdf/1204.6079.pdf) paper. There might be some use cases that require an additional table in order to produce output. As you said, extracting a substring and finding the match of this substring in another table (or dictionary), then providing the desired output accordingly. (Example 6 in the same paper again) I've tried to perform similar semantic transformations in this paper with PROSE. Although it returns a program, basically tries to transform syntactically. I have specified the rows of related tables as additional inputs and added as a constraint to the session. (I think here, I need to declare these additional inputs as lookup dictionary or something similar but unfortunately, do not know how to do that)
Thank you again for your help!

**Comment by danpere** [comment]
Since it isn't supported, there's no way to specify a lookup table of that kind. The PROSE way of doing so would probably be to add a `Constraint` type that provides a lookup table along with a new operator and witness functions to actually make use of that lookup table.

**Comment by aslihanozmen** [comment]
Thank you for the clarification. I will try the PROSE way!

**Comment by danpere** [comment]
I'm sorry I was unclear. The feature you are requesting is not supported in PROSE. To get it working in PROSE there are two options:
1. We would have to add it to Transformation.Text in a future release (we are not presently planning to do so) or
2. You would have to implement a whole new DSL which supports that operator.
