### ISSUE TITLE
Setting recursion limits of grammars

### ISSUE THREAD

**Issue by wslee** [microsoft/prose#33]
Hello and thank you very much for the great framework! 

I have defined a recursive DSL grammar, and want to make the search space finite by limiting depth and "unrolling" the grammar finite times.
Perhaps could I do that by annotating production rules of the grammar? Then, what kinds of keywords can I use when using the DSL compiler?

**Comment by vuminhle** [comment]
Thanks for your nice words and questions.

You can annotate the (recursive) argument with `@recurse[int]` to limit the number of unrolling.
For instance, 
```
string s := const
         | Concat(const, @recurse[3] s);
```

**Comment by wslee** [comment]
@vuminhle Thank you so much! It works well :)
