### ISSUE TITLE
DslAuthoringTutorial Confused by `substring-` prefix in folders.

### ISSUE THREAD

**Issue by Fraser-Greenlee** [microsoft/prose#37]
The tutorial says there are folders named `substring-part1a`, `substring-part2b`, etc which I haven't found.

Should these be changed to remove `substring-`, just saying `part1a`?

**Comment by danpere** [comment]
Yes. I just pushed 8da6df9982c5e898f06a3580b6a6310b23e8d794 which fixes this. Thank you for the correction.
