### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by OlivlfilipeOliveira** [microsoft/prose#41]
Can you tell me how to solve this? (image attached)

![Anotação 2020-02-07 115921](https://user-images.githubusercontent.com/17935140/74028149-72492e80-4988-11ea-80f3-9ae0d7d38e46.png)

**Comment by danpere** [comment]
Odd. I get the same error. (Note: In the exception settings, enabling all "Common Language Runtime Exceptions" makes the debugger show you the actual initial exception.) The straightforward workaround is to just change the path on line 20:
```cs
            InputGrammarText = File.ReadAllText("../../../synthesis/grammar/substring.grammar"),
```
But I'm not sure why that's necessary...

**Comment by OlivlfilipeOliveira** [comment]
> Odd. I get the same error. (Note: In the exception settings, enabling all "Common Language Runtime Exceptions" makes the debugger show you the actual initial exception.) The straightforward workaround is to just change the path on line 20:
> 
> ```cs
>             InputGrammarText = File.ReadAllText("../../../synthesis/grammar/substring.grammar"),
> ```
> 
> But I'm not sure why that's necessary...

so I'm going to put the same grammar path that is in the code?
