### ISSUE TITLE
Error in Building ProseSample.sln

### ISSUE THREAD

**Issue by tkbala** [microsoft/prose#43]
I am trying to build ProseSample.sln, but I get the following error

> The type or namespace name 'Language' does not exist in the namespace 'ProseSample.Substrings'

I had downloaded the master branch of the repository from GitHub. Then Opened the ProseSample.sln file using Visual Studio 2019. Then I changed the Target framework to .NET Core 3.1 for 'ProseSample', 'ProseSample.Substrings', 'ProseSample.Substrings.Semantics' and 'ProseSample.TextExtraction'.

I also verified that the following NuGet packages are installed for the project: 
Microsoft.ProgramSynthesis, Microsoft.ProgramSynthesis.Common, Microsoft.ProgramSynthesis.Compiler and Microsoft.ProgramSynthesis.Dslctargets

**Comment by danpere** [comment]
I get the same error in Visual Studio if I don't build from the command-line first (`dotnet build ProseSamples.sln`). If you have already built from Visual Studio, you may have to clean first (`git clean -fdx` will clean everything). Hopefully this workaround should get you working for now.

`dslc` (the DSL compiler part of PROSE) involves being a bit too fancy with MSBuild so it acts strangely like that sometimes, sorry.

**Comment by tkbala** [comment]
Great! This works! Thanks @danpere :D
