### ISSUE TITLE
Solution file of  PROSE not getting loaded is solution explorer in new version of Visual Studio i.e. 17.8.2

### ISSUE THREAD

**Issue by thatsSudhanshu** [microsoft/prose#72]
when I try to open any solution file in Visual studio ,it is not getting loaded saying unloaded in new version of Visual Studio i.e. 17.8.2 . can you please specify which version of visual Studio will work fine for it.
![Screenshot (243)](https://github.com/microsoft/prose/assets/152074422/2e531687-bd6f-4fc8-9d50-88bc3696d83b)

**Comment by danpere** [comment]
Apologies, we still have a dependency on [.NET Core 2.1](https://dotnet.microsoft.com/en-us/download/dotnet/2.1)---which is out of support---for compiling DSLs. You can install it and the samples should work, although they'll give you warnings about using an old an out of support version of .NET.

(We are actively working on removing that dependency and hopefully it will be gone within a few releases.)

**Comment by thatsSudhanshu** [comment]
> Apologies, we still have a dependency on [.NET Core 2.1](https://dotnet.microsoft.com/en-us/download/dotnet/2.1)---which is out of support---for compiling DSLs. You can install it and the samples should work, although they'll give you warnings about using an old and out of support version of .NET.
> 
> (We are actively working on removing that dependency and hopefully it will be gone within a few releases.)
