### ISSUE TITLE
Extracting one (or more) regions of the same type from each new file

### ISSUE THREAD

**Issue by eglassman** [Microsoft/prose#9]
Hi!

I want to extract one (or more) regions of the same type from each new file. Below, I have code that demonstrates how the first two examples contain one region to extract and the third example contains two. However, I'm getting a `System.ArgumentException` when calling the `RegionLearner.Instance.Learn()` on the examples because there are two items with the same key (probably the two regions from the same input file). 

I'm using the library incorrectly; the docstring for `LearnRegion()` confirms that it can only learn a single region per file. None of the other example function calls appear to model what I want.

What do you recommend?

Cheers,
Elena

```
string text0 = File.ReadAllText("training_samples/training_sample_0.html");
			string text1 = File.ReadAllText("training_samples/training_sample_1.html");
			string text2 = File.ReadAllText("training_samples/training_sample_2.html");

			var input0 = RegionLearner.CreateStringRegion(text0);
			var input1 = RegionLearner.CreateStringRegion(text1);
			var input2 = RegionLearner.CreateStringRegion(text2);

			var extractedRegion0_b = input0.Slice(107, 170);
			var extractedRegion1_b = input1.Slice(228, 305);
			var extractedRegion2_b = input2.Slice(225, 293);
			var extractedRegion3_b = input2.Slice(294, 366);

			//Console.WriteLine(extractedRegion0_b.ToString());
			//Console.WriteLine(extractedRegion1_b.ToString());

			//return;

			var examples_b = new[] {
				new CorrespondingMemberEquals<StringRegion, StringRegion>(input0, extractedRegion0_b), // "Carrie Dodson 100" => "Dodson"
				new CorrespondingMemberEquals<StringRegion, StringRegion>(input1, extractedRegion1_b), // "Leonard Robledo 75" => "Robledo"
				new CorrespondingMemberEquals<StringRegion, StringRegion>(input2, extractedRegion2_b), // "Leonard Robledo 75" => "Robledo"
				new CorrespondingMemberEquals<StringRegion, StringRegion>(input2, extractedRegion3_b) // "Leonard Robledo 75" => "Robledo"
            };


			RegionProgram topRankedProg_b = RegionLearner.Instance.Learn(examples_b);
```

**Comment by apskim** [comment]
If I understand correctly, you want to extract a _sequence_ of regions from a single file. Check out `SequenceLearner`. There is a lot of sample code in the same project that uses it.

**Comment by eglassman** [comment]
I don't think of it as a sequence, but if it works, it doesn't matter what I think it is. Thanks Alex, I'll try it!


via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.59&pv=7.1.1&source=email_footer_2] On Fri, Feb 03, 2017 at 9:22pm, Alex Polozov < notifications@github.com [notifications@github.com] > wrote:
If I understand correctly, you want to extract a sequence of regions from a single file. Check out SequenceLearner . There is a lot of sample code in the same project that uses it.
